development:
  adapter: postgresql
  encoding: unicode
  database: blog_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: blog_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: blog_production
  pool: 5